# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0ccc86f620f35c24284ea534502865742ec06437c482dafd66725306db50d55bbe356c6f948c780f609b367f48983eb8a46bf83307cc22572531b245758f253

test:
  secret_key_base: 1330e9558a5297d5364185fee27286e6de5d0f6dbc27e0f2de79a25d59b5652e0f83e763b25f29179d49c1ff83afc845861c3925b4e0d224c1a0a5344b0e904f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
