# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b06e64314beed97e708b855b55900131fd706c26cabb3f219241665b94923709b3153e1771e406a0abfd94e0b00d8f7c9d33a6c3e14e14afdb4d2f364b0d70f0

test:
  secret_key_base: c784a727900d50e2817eb69f0bb0e7f66a458435fae0152eafcc0cfb77983424ae092d7e66797dde04c13dda75952c0b036ec198450e75bf90b71d38bc78a634

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
